site_name: Apuntes de Aplicaciones Web &copy;Antonio Díaz Santamaría  
site_author: Antonio Díaz Santamaría  
theme:  
  name: 'material'  
  code:  
    highlighting: monokai  # Cambia "monokai" por el estilo que prefieras  
  palette:  
    primary: 'indigo'  # Color primario  
    accent: 'red'      # Color de acento  
  features:  
    - navigation.sections  # Expansión y colapso de las secciones  
    - navigation.instant   # Desplazamiento rápido  
extra_css:  
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear  
  - 'assets/css/stylesheets.css'
nav:  
  - Índice: 'index.md'  
  - Unidad 4:  
      - 4.1 Conceptos Básicos:   
          - 4.1.1 Introducción: 'u04/04-01-01.md'
          - 4.1.2 WP-ORG vs WP-COM: 'u04/04-01-02.md'  
          - 4.1.3 Dominios y Hosting: 'u04/04-01-03.md'  
      - 4.2 Interfaz de WP:  
          - 4.2.1 Introducción: 'u04/04-02-01.md'
          - 4.2.2 Panel de Administración: 'u04/04-02-02.md'  
          - 4.2.3 Barra Superior: 'u04/04-02-03.md'
          - 4.2.4 Menú Lateral: 'u04/04-02-04.md'
          - 4.2.5 Área de Trabajo: 'u04/04-02-05.md'
          - 4.2.6 Pie de Página: 'u04/04-02-06.md'
      - 4.3 Editor de Contenido y Gestión:
          - 4.3.1 Editor de Contenido: 'u04/04-03-01.md'
          - 4.3.2 Personalización del Sitio: 'u04/04-03-02.md'
          - 4.3.3 Configuracion general: 'u04/04-03-03.md'
      - 4.4 Administración y Configuración:
          - 4.4.1 Entradas: 'u04/04-04-01.md'
          - 4.4.2 Páginas: 'u04/04-04-02.md'
          - 4.4.3 Gestión de Medios: 'u04/04-04-03.md'
          - 4.4.4 Gestión de Usuarios: 'u04/04-04-04.md'
          - 4.4.5 Apariencia: 'u04/04-04-05.md'
          - 4.4.6 Configuración de Seguridad: 'u04/04-04-06.md'
          - 4.4.7 Copias de Seguridad: 'u04/04-04-07.md'
          - 4.4.8 Creación y Configuración de Foros: 'u04/04-04-08.md'
      - 4.5 Temas y Plantillas:
          - 4.5.1 ¿Qué es un tema en WordPress?: 'u04/04-05-01.md'
          - 4.5.2 Instalación y activación de temas: 'u04/04-05-02.md'
          - 4.5.3 Personalización de temas: 'u04/04-05-03.md'
          - 4.5.4 ¿Qué es un tema hijo?: 'u04/04-05-04.md'
          - 4.5.5 Elementos clave de un tema: 'u04/04-05-05.md'
          - 4.5.6 Plugins de creación visual: 'u04/04-05-06.md'
      - 4.6 Plugins:
          - 4.6.1 ¿Qué es un plugin?: 'u04/04-06-01.md'
          - 4.6.2 Instalación y Activación de Plugins: 'u04/04-06-02.md'
          - 4.6.3 Tipos de Plugins Comunes: 'u04/04-06-03.md'
          - 4.6.4 Configuración Básica de un Plugin: 'u04/04-06-04.md'
      - 4.7 SEO y Optimización Web:
          - 4.7.1 ¿Qué es el SEO?: 'u04/04-07-01.md'
          - 4.7.2 Principios básicos de SEO: 'u04/04-07-02.md'
          - 4.7.3 Herramientas de SEO en WordPress: 'u04/04-07-03.md'
          - 4.7.4 Optimización del rendimiento: 'u04/04-07-04.md'
          - 4.7.5 SEO técnico: 'u04/04-07-05.md'


