site_name: Apuntes de Aplicaciones Web &copy;Antonio Díaz Santamaría  
site_author: Antonio Díaz Santamaría  
theme:  
  name: 'material'  
  code:  
    highlighting: monokai  # Cambia "monokai" por el estilo que prefieras  
  palette:  
    primary: 'indigo'  # Color primario  
    accent: 'red'      # Color de acento  
  features:  
    - navigation.sections  # Expansión y colapso de las secciones  
    - navigation.instant   # Desplazamiento rápido  
extra_css:  
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear  
  - 'assets/css/stylesheets.css'
nav:  
  - Índice: 'index.md'  
  - Unidad 4:  
      - 4.1 Conceptos Básicos:   
          - 4.1.1 Introducción: 'u04/04-01-01.md'
          - 4.1.2 WP-ORG vs WP-COM: 'u04/04-01-02.md'  
          - 4.1.3 Dominios y Hosting: 'u04/04-01-03.md'  
      - 4.2 Interfaz de WP:  
          - 4.2.1 Introducción: 'u04/04-02-01.md'
          - 4.2.2 Panel de Administración: 'u04/04-02-02.md'  
          - 4.2.3 Barra Superior: 'u04/04-02-03.md'
          - 4.2.4 Menú Lateral: 'u04/04-02-04.md'
          - 4.2.5 Área de Trabajo: 'u04/04-02-05.md'
          - 4.2.6 Pie de Página: 'u04/04-02-06.md'
      - 4.3 Editor de Contenido y Gestión:
          - 4.3.1 Editor de Contenido: 'u04/04-03-01.md'
          - 4.3.2 Personalización del Sitio: 'u04/04-03-02.md'
          - 4.3.3 Configuracion general: 'u04/04-03-03.md'


