site_name: Apuntes de Aplicaciones Web &copy;Antonio Díaz Santamaría
site_author: Antonio Díaz Santamaría
theme:
  name: 'material'
  code:
    highlighting: monokai  # Cambia "monokai" por el estilo que prefieras
  palette:
    primary: 'indigo'  # Color primario
    accent: 'red'      # Color de acento
  features:
    - navigation.sections  # Expansión y colapso de las secciones
    - navigation.instant   # Desplazamiento rápido
extra_css:
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear
nav:
  - Índice: 'index.md'
  - Unidad 4:
      - 4.1. Introducción: 'u04/u04_01.md'
      - 4.2. WP-ORG vs WP-COM: 'u04/u04_02.md'

